Makefile
plugins/tests/integration/oidc_test.go

ci: add dependency check

---

pkg/consumer/consumer.go
pkg/filtermanager/api/api.go
pkg/filtermanager/filtermanager.go
plugins/oidc/filter.go
plugins/tests/pkg/envoy/capi.go

Also clarify the concurrent safe of the fm API

fix race in update/lookup consumer

---

controller/internal/istio/envoyfilter.go
controller/internal/istio/testdata/default_filters.yml
controller/internal/translation/merged_state.go
controller/internal/translation/testdata/plugins/bandwidth_limit.out.yml
controller/internal/translation/testdata/plugins/buffer.out.yml
controller/internal/translation/testdata/plugins/inner_lua.out.yml
controller/internal/translation/testdata/plugins/local_ratelimit.out.yml
controller/internal/translation/testdata/plugins/outer_lua.out.yml
controller/internal/translation/testdata/translation/consumer.out.yml
controller/internal/translation/testdata/translation/httproute.out.yml
controller/internal/translation/testdata/translation/httproute_both_no_hostnames.out.yml
controller/internal/translation/testdata/translation/httproute_no_hostnames.out.yml
controller/internal/translation/testdata/translation/merge_same_level_httpfilterpolicy.out.yml
controller/internal/translation/testdata/translation/native_plugin_only.out.yml
controller/internal/translation/testdata/translation/post_native_plugin_and_go_plugin.out.yml
controller/internal/translation/testdata/translation/pre_native_plugin_and_go_plugin.out.yml
controller/internal/translation/testdata/translation/virtualservice.out.yml
controller/internal/translation/testdata/translation/virtualservice_and_section_name.out.yml
controller/internal/translation/testdata/translation/virtualservice_section_name.out.yml
controller/internal/translation/testdata/translation/virtualservice_section_name_share_host.out.yml
controller/internal/translation/testdata/translation/virtualservice_share_host.out.yml
controller/internal/translation/testdata/translation/virtualservice_wildcard_gateway.out.yml
controller/internal/translation/testdata/translation/virtualservice_wildcard_host.out.yml
controller/internal/translation/translation_test.go
etc/demo.yaml
examples/dev_your_plugin/etc/demo.yaml
plugins/tests/integration/control_plane/control_plane.go
plugins/tests/integration/data_plane/bootstrap.yml
plugins/tests/integration/ext_auth_route.yml

This avoids conflicts with istio

Rename our generated envoy http filter to use htnn prefix

---

site/content/zh-hans/docs/operations-guide/controller/_index.md

Unite the Chinese translation of Controller

---

controller/internal/controller/httpfilterpolicy_controller.go

Setting status twice will trigger a change event but nothing needs to be changed. This causes an error "the object has been modified".

avoid setting status twice

---

.gitignore
controller/Makefile
controller/cmd/main.go
controller/config/manager/manager.yaml
controller/internal/config/config.go
controller/internal/log/log.go
controller/internal/log/log_test.go
controller/internal/registry/registry.go
controller/internal/registry/store.go
controller/pkg/registry/registry.go
controller/registries/nacos/config.go

Prepare for the next step of breaking down

controller: use own log lib

---

controller/cmd/main.go
controller/config/config.default.yaml
controller/config/manager/manager.yaml
controller/internal/config/config.go
controller/internal/config/config_test.go
controller/internal/config/testdata/config.yaml
controller/internal/controller/httpfilterpolicy_controller.go
controller/tests/integration/controller/suite_test.go

For env which doesn't need gw api, we don't force user to install the CRDs.

controller: let gateway api be optional

---

api/plugins/tests/integration/data_plane/data_plane.go

This fix is required by https://github.com/mosn/htnn/pull/452

don't hardcode the path of libgolang.so

---

Makefile
controller/Makefile
tools/cmd/linter/main.go

1. don't lint the proto under external/istio
2. make sure the crd is successfully downloaded

improve dev experience

---

controller/tests/benchmark/httpfilterpolicy_controller_test.go
types/apis/v1/validation_test.go

Fix https://github.com/mosn/htnn/issues/429

Replace some basic gateway API types with gwapiv1 from gwapiv1a2

---

.licenserc.yaml
Makefile

correct dep check config

---

patch/istio/1.21/20240410-htnn-go-mod.patch

If it doesn't work well, we can pin them back

don't pin istio/k8s deps

---

.github/workflows/build-and-push-dev-image.yml

This format is also used by Envoy

build: change unique tag format to avoid conflict

---

api/Makefile
api/plugins/tests/integration/data_plane/data_plane.go
examples/dev_your_plugin/Makefile
plugins/Makefile
site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md

Also unite the name of the custom image.

fix(integration-test): didn't pull correct image when a different image is given

---

api/pkg/filtermanager/filtermanager.go
api/pkg/plugins/plugins.go
controller/tests/integration/controller/httpfilterpolicy_controller_gateway_test.go
types/apis/v1/validation.go
types/apis/v1/validation_test.go

This commit just changes err msg & field names.

chore: there are access filters which also can't added by Consumer

---

.github/workflows/stale.yml

fixes: https://github.com/mosn/htnn/issues/584

Change the stale bot to run once per day

---

.github/workflows/lint.yml

resolve: https://github.com/mosn/htnn/issues/132 
use gha https://github.com/reviewdog/action-shellcheck to check shell scripts.

ci: add shellcheck

---

controller/internal/translation/init_state.go
e2e/Makefile
e2e/base/default.yml
e2e/htnn_controller_values.yaml
e2e/pkg/suite/suite.go
e2e/port-forward.sh
e2e/tests/httproute_other_namespace.go
e2e/tests/policy_to_tcp_proxy.go
e2e/tests/policy_to_tcp_proxy.yml

Support using L4 policy to TCP proxy created by Gateway API

---

api/pkg/filtermanager/filtermanager.go
api/plugins/tests/integration/dataplane/bootstrap.go
api/plugins/tests/pkg/envoy/capi.go
api/tests/integration/filtermanager_test.go

feat: record plugin name which sends local reply

---

MAINTAIN.md
Makefile
examples/dev_your_plugin/cmd/libgolang/main.go
examples/dev_your_plugin/etc/demo.yaml
examples/dev_your_plugin/go.mod
examples/dev_your_plugin/go.sum
examples/dev_your_plugin/plugins/your_plugin.go
examples/dev_your_plugin/tests/integration/suite_test.go
examples/dev_your_plugin/tests/integration/your_plugin_test.go
site/content/en/docs/developer-guide/get_involved.md
site/content/zh-hans/docs/developer-guide/get_involved.md

should update the example to use the released version

---

go.work

chore: we don't remove go.work during release now

---

e2e/pkg/suite/suite.go

Solve flaky tests in:
https://github.com/mosn/htnn/actions/runs/10383687374/job/28749117873

e2e: increase wait time to make it stable

---

.github/workflows/lint.yml
Makefile
manifests/charts/htnn-controller/templates/crds/htnn.mosn.io_consumers.yaml
manifests/charts/htnn-controller/templates/crds/htnn.mosn.io_filterpolicies.yaml
manifests/charts/htnn-controller/templates/crds/htnn.mosn.io_httpfilterpolicies.yaml
manifests/charts/htnn-controller/templates/crds/htnn.mosn.io_serviceregistries.yaml

Next time, we should let the contributor to merge main, ensure the CI is passed

fix broken CI caused by upgrading controller-gen

---

controller/pkg/istio/istio.go

controller: fix typo in var name

---

patch/README.md
patch/istio/1.21/20240912-optimize-xds-generation.patch

This change is missed when those CRDs are first added.

add patch to avoid unnecessary xDS generation for our CRD

---

site/content/en/docs/reference/registries/nacos.md
site/content/zh-hans/docs/reference/registries/nacos.md

ref https://github.com/mosn/htnn/issues/258

docs: update the nacos v2 

---

site/content/en/docs/concept/dynamic_config.md
site/content/zh-hans/docs/concept/dynamic_config.md

DynamicConfig: add doc

---

Makefile
site/content/en/docs/concept/dynamic_config.md
site/content/zh-hans/docs/concept/dynamic_config.md

ci: fix markdownlint

---

plugins/pkg/request/request.go

correct interface type passed to the GetHeaders

---

api/pkg/filtermanager/api/result_action.go
examples/dev_your_plugin/Makefile
examples/dev_your_plugin/cmd/libgolang/main.go
examples/dev_your_plugin/go.mod
examples/dev_your_plugin/go.sum
examples/dev_your_plugin/plugins/your_plugin.go
examples/dev_your_plugin/verify.sh
plugins/plugins/demo/filter.go
site/content/en/docs/developer-guide/plugin_development.md

This is a follow up PR to https://github.com/mosn/htnn/pull/742
Fix #[issue]

Enhance the plugin example with more interfaces

---

api/pkg/filtermanager/filtermanager.go
api/pkg/filtermanager/filtermanager_test.go

In the previous Envoy API, we can get the request's Content-Type header lazily. However, in the new APi we have to get it in the hot path. We don't local reply in encode phases for now, not even say considering the request header.

change: don't respect the req's ct when local reply in encode phases

---

api/plugins/tests/integration/controlplane/control_plane.go
api/tests/integration/api_test.go
api/tests/integration/benchmark_test.go
api/tests/integration/consumer_test.go
api/tests/integration/filtermanager_test.go
api/tests/integration/http_filter_test.go
examples/dev_your_plugin/tests/integration/your_plugin_test.go
plugins/tests/integration/casbin_test.go
plugins/tests/integration/cel_script_test.go
plugins/tests/integration/consumer_restriction_test.go
plugins/tests/integration/debug_mode_test.go
plugins/tests/integration/demo_test.go
plugins/tests/integration/ext_auth_test.go
plugins/tests/integration/hmac_auth_test.go
plugins/tests/integration/key_auth_test.go
plugins/tests/integration/limit_count_redis_test.go
plugins/tests/integration/limit_req_test.go
plugins/tests/integration/oidc_test.go
plugins/tests/integration/opa_test.go

[typo] Pluin -> Plugin

---

api/pkg/filtermanager/filtermanager.go
site/content/en/docs/developer-guide/plugin_development.md
site/content/zh-hans/docs/developer-guide/plugin_development.md

clarify the relationship between DecodeData & DecodeRequest and more

---

patch/istio/1.21/20240410-embed-htnn-controller-go-code.patch

fix typo in patch

---

api/plugins/tests/integration/dataplane/bootstrap.go

test: add ability to specify extra cluster

---

site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md

doc: fix plugin_integration_test_framework.md

---

.github/workflows/lint.yml
Makefile

- Add `lint-yaml` target in Makefile to lint YAML files, ignoring Helm template YAML files
- Update GitHub Actions workflow to include YAML lint step
We don’t use `if ! command -v yamllint` because some environments might have a pre-installed Python version. Checking the specific path ensures we're using the Node.js version to avoid conflicts.
Close #128

feat(makefile, workflows): add YAML linter to workflow and Makefile

---

.github/workflows/test.yml
controller/Makefile
controller/tests/integration/helper/helper.go

test: unite the task name

---

tools/cmd/linter/main.go
types/plugins/plugins_test.go

ci: improve linter & avoid crash with garbage input

---

.github/workflows/build-and-push-dev-image.yml
Makefile
manifests/images/cp/Dockerfile
manifests/images/dp/Dockerfile
patch/istio/1.21/20240410-htnn-go-mod.patch

dev: fix broken 'make prebuild'

---

api/pkg/filtermanager/model/model.go
api/pkg/filtermanager/wrapper.go
api/pkg/filtermanager/wrapper_test.go
plugins/plugins/debugmode/filter.go
plugins/tests/integration/debug_mode_test.go

debugmode: reduce the data we collect

---

CODEOWNERS

add @WeixinX as the owner of sentinel

---

.github/PULL_REQUEST_TEMPLATE.md

dev: make Fix #[issue] optional

---

.github/workflows/build-and-push-dev-image.yml
.github/workflows/lint.yml
.github/workflows/release-branch.yml
.github/workflows/release-tag.yml
.github/workflows/test.yml
.golangci.yml
Makefile
common.mk
e2e/Makefile
manifests/Makefile
patch/apply-patch.sh

ci: test with Go 1.22

---

api/pkg/filtermanager/filtermanager.go
api/pkg/filtermanager/filtermanager_benchmark_test.go
api/pkg/filtermanager/model/model.go
api/pkg/filtermanager/wrapper.go
api/pkg/filtermanager/wrapper_test.go
plugins/plugins/debugmode/filter.go

According to the micro benchmark BenchmarkFilterManagerDebugEnabled, 50% faster compared with the main branch.

optimize execution time recording

---

site/content/en/docs/concept/filterpolicy.md
site/content/en/docs/developer-guide/plugin_development.md
site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/concept/filterpolicy.md
site/content/zh-hans/docs/developer-guide/plugin_development.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md
tools/cmd/linter/main.go

doc: add debug notes

---

site/content/zh-hans/docs/developer-guide/plugin_development.md

close https://github.com/mosn/htnn/issues/750

docs: complement package name to variables' types

---

e2e/htnn_controller_values.yaml

It provides false positive report as decribed in
https://github.com/istio/istio/issues/53050

e2e: drop UNSAFE_PILOT_ENABLE_DELTA_TEST check

---

api/pkg/filtermanager/wrapper.go

debugMode: protect record with lock

---

api/plugins/tests/integration/dataplane/bootstrap.go
api/plugins/tests/integration/dataplane/data_plane.go

test: fix problems of integration test binary mode impl

---

types/plugins/demo/config.go
types/plugins/limitcountredis/config.go
types/plugins/oidc/config.go

add NonBlockingPhases mark to plugins

---

api/pkg/filtermanager/api/result_action.go
api/pkg/filtermanager/filtermanager.go
api/tests/integration/filtermanager_test.go
api/tests/integration/test_plugins.go

filtermanager: support setting details in LocalResponse

---

types/apis/v1/validation.go
types/apis/v1/validation_test.go

fix: should reject bad FilterSubPolicy

---

api/pkg/filtermanager/api/phase.go
api/pkg/filtermanager/filtermanager.go

filtermanager: enrich log for handleAction

---

api/pkg/filtermanager/api/result_action.go
api/pkg/filtermanager/filtermanager.go

filtermanager: expose default resp for being decoded elsewhere

---

.github/workflows/stale.yml

ci: provide a way to mark PR as no stale

---

.github/dependabot.yml
common.mk

This solves security alert: https://github.com/mosn/htnn/security/dependabot/19.

chore: track examples & tests in dependabot

---

api/pkg/filtermanager/api/result_action.go
api/pkg/filtermanager/filtermanager.go
api/pkg/filtermanager/filtermanager_test.go
api/plugins/tests/pkg/envoy/capi.go

enable waiting for the first part of data in EncodeHeader

---

.github/dependabot.yml

ci: reduce unnessary updates

---

.github/workflows/test.yml
api/go.mod
api/go.sum
api/pkg/filtermanager/api/api.go
api/pkg/filtermanager/api/api_129.go
api/pkg/filtermanager/api/api_131_132.go
api/pkg/filtermanager/api_impl_129.go
api/pkg/filtermanager/api_impl_131_132.go
api/pkg/plugins/type.go
api/plugins/tests/integration/test_binary_mode.sh
api/plugins/tests/pkg/envoy/capi.go
patch/switch-envoy-go-version.sh

catch up the latest Envoy

---

maintainer/guide.md

add doc about adapting latest Envoy

---

api/pkg/filtermanager/wrapper.go

don't compute ID each time when log level is debug

---

e2e/htnn_controller_values.yaml

Configure the istiod in e2e to push aggressively.
Just changing the controller's values file used in e2e.
Fix #619

configure the istiod in e2e to push aggressively
