mosn/htnn

.github/workflows/stale.yml

The stale rule follows the Envoy's rule.

enable stale bot

---

.github/dependabot.yml

It's meaningless because we still have break change.

drop auto-update dependabot for examples

---

controller/internal/controller/httpfilterpolicy_controller.go
controller/internal/translation/data_plane_state.go
controller/internal/translation/testdata/translation/httproute.in.yml
controller/tests/integration/controller/httpfilterpolicy_controller_test.go
controller/tests/integration/controller/suite_test.go
controller/tests/integration/controller/testdata/httpfilterpolicy/httproute_without_gateway.yml

The previous way can't handle HTTPRoute in time, as the status is written after istio has processed the resource.

Handle HTTPRoute directly according to its spec

---

api/plugins/tests/integration/data_plane/data_plane.go
site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md

This cause unusablity when using the framework outside this project.

Don't hardcode the project root location

---

api/pkg/plugins/plugins.go
controller/config/config.default.yaml
controller/internal/config/config.go
controller/internal/config/config_test.go
controller/internal/config/testdata/config.yaml
controller/tests/integration/controller/httpfilterpolicy_controller_test.go
controller/tests/integration/controller/suite_test.go
controller/tests/integration/controller/testdata/httpfilterpolicy/native_plugin.yml

Sometimes we may need to disable all native plugins, because:
1. Only want to use Go plugins
2. A custom Envoy is used and it doesn't support all Envoy's http filters as the default open source one.

controller: add option to disable native plugin

---

.github/dependabot.yml

Only get security updates for a single module is meaningless because other modules may already update a newer dependency. So better to follow other modules' style.

change /controller's dependabot rule to be equal others

---

api/Makefile
api/plugins/tests/integration/data_plane/data_plane.go
examples/dev_your_plugin/Makefile
plugins/Makefile

For e2e test, we just need to run `istioctl manifest` or something else to change the images used by istio.

add ability to run integration test with custom image

---

e2e/base/default.yml

The cabundle injector injects the webhook by the label, so we can solve this by providing the label.

e2e: don't hijack istio's own webhook

---

.github/workflows/lint.yml
.github/workflows/test.yml
MAINTAIN.md

The commit https://github.com/mosn/htnn/commit/ae4829cbf34cada3ce024f039b8cacad129ae962 doesn't get rid of them completely.

get rid of submodule from CI & docs

---

api/plugins/tests/integration/data_plane/data_plane.go
api/plugins/tests/integration/data_plane/data_plane_test.go

Previously, when make integration-test is called without building the shared library, an empty directory is created, which will cause the new so created inside this directory, and cause the next `make integration-test` to fail.

detect shared library to avoid creating an empty libgolang directory

---

patch/istio/1.21/20240410-htnn-go-mod.patch
types/apis/v1/validation.go
types/apis/v1/validation_test.go

Now there will not be logs like `register plugin xxx` when running unit tests.

don't run the `init` function in the plugins' package

---

controller/tests/testdata/services/docker-compose.yml
plugins/tests/integration/testdata/services/docker-compose.yml
site/docker-compose.yaml

See https://news.ycombinator.com/item?id=40196989
This suppresses a warning when we run docker-compose.

chore: remove obsolete docker compose version

---

.github/workflows/test.yml
.gitignore
Makefile
common.mk
controller/Makefile
e2e/Makefile
e2e/istio.sh
site/Makefile

Fix #426 
I am working on issue #426.
I hope that my work is on the right track. I have thoroughly run every makefile command related to the project to ensure everything is functioning correctly.
Looking forward to your feedback and hoping my contribution is valuable.
Thank you!

chore: unite the bin cache dir for all projects in go.work

---

.github/workflows/lint.yml
tools/Dockerfile.dev
tools/cmd/linter/main.go

The hadolint action will notify developers even this is an info level report.

chore: improve lint err msg & solve annoying notifications

---

.github/workflows/website.yml
.gitignore
Makefile

It was broken since https://github.com/mosn/htnn/commit/6109acdea2f10eff86632c54baa3c97573156edf

ci: fix broken website link check

---

patch/istio/1.21/20240410-htnn-go-mod.patch

This is synced from the internal fork.

downgrade dependencies that break the UT of istio

---

api/plugins/tests/integration/helper/helper.go
controller/Makefile
plugins/Makefile
site/Makefile
site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md

GitHub Action no longer supports this command.
See https://github.com/orgs/community/discussions/116610
This fixes the broken CI.

ci: don't use deprecated docker-compose

---

e2e/htnn_controller_values.yaml
e2e/pkg/suite/suite.go

Fix https://github.com/mosn/htnn/issues/659

e2e: solve the flaky consumer test

---

api/pkg/filtermanager/api/api.go
api/pkg/filtermanager/api_impl.go
api/pkg/filtermanager/api_impl_test.go
api/plugins/tests/pkg/envoy/capi.go

feat(filtermanager): add way to inject log args

---

tools/gen-crd-code.sh

ci: fix stale GOROOT used by client-gen

---

api/internal/consumer/mock.go
api/pkg/filtermanager/api_impl.go
api/pkg/filtermanager/api_impl_test.go

Otherwise, the recorded exec time is incorrect after recycling.

fix: should reset pluginState and other fields

---

patch/README.md
patch/istio/1.21/20240823-server-side-filter.patch

This feature is developed by @lhanjian

add server side filter patch

---

controller/registries/consul/config_test.go
controller/tests/testdata/services/docker-compose.yml

The ut will crash with `SIGBUS: bus error` on Mac. Use `defer` solve
this problem.

improve the UX of consul test

---

controller/internal/controller/consumer_controller.go
controller/tests/integration/controller/consumer_controller_test.go
controller/tests/integration/controller/testdata/consumer/consumer_name_conflict.yml
e2e/tests/consumer.go
e2e/tests/consumer.yml
manifests/charts/htnn-controller/templates/crds/htnn.mosn.io_consumers.yaml
types/apis/v1/consumer_types.go

This make it possible to contain special info in the name of k8s custom resource, which is different from the name used in the request matching. This feature is useful with server side filter.

consumer: allow specifying different name when writing to k8s

---

controller/registries/nacos/v1/config.go
controller/registries/nacos/v1/config_test.go
controller/tests/integration/controller/consumer_controller_test.go

test: ensure the correct EnvoyFilter is kept & improve Nacos config test

---

.github/workflows/test.yml
common.mk

ci: work around race bug

---

examples/dev_your_plugin/Makefile
examples/dev_your_plugin/cmd/libgolang/main.go
examples/dev_your_plugin/go.mod
examples/dev_your_plugin/go.sum
plugins/plugins/demo/filter.go

update example to adapt Envoy 1.31

---

e2e/Makefile
e2e/kind_cluster.yaml
manifests/charts/htnn-controller/README.md
manifests/charts/htnn-controller/values.schema.json
manifests/charts/htnn-controller/values.yaml

So we can connect to IPv6 upstream

enable dual stack by default

---

e2e/go.mod
e2e/go.sum
e2e/tests/consumer.go

e2e: retry to solve timeout

---

controller/internal/istio/envoyfilter.go
controller/internal/model/model.go
controller/internal/translation/merged_state.go
controller/plugins/plugins.go
controller/plugins/routepatch/config.go
controller/plugins/testdata/http/route_patch.in.yml
controller/plugins/testdata/http/route_patch.out.yml
e2e/Makefile
e2e/base/nacos.yml
e2e/pkg/suite/suite.go
e2e/tests/route_patch.go
e2e/tests/route_patch.yml
manifests/Makefile
manifests/images/cp/Dockerfile
manifests/images/dp/Dockerfile
types/plugins/plugins.go
types/plugins/routepatch/config.go

add routePatch plugin

---

api/pkg/plugins/plugins.go
controller/internal/translation/testdata/translation/virtualservice_subpolicies.out.yml

fix: the plugin order sent from controller may be wrong

---

api/pkg/filtermanager/filtermanager_dev.go

fix: change inner req hdr caused race

---

api/plugins/tests/integration/dataplane/bootstrap.yml

fix host.docker.internal resolve as ip v6 address in docker v4.31.0, see docker issue[7332](https://github.com/docker/for-mac/issues/7332)

Update bootstrap.yml to fix host.docker.internal resolve as ip v6 address in docker v4.31.0

---

controller/internal/translation/merged_state_test.go
controller/internal/translation/testdata/translation/policy_order.in.yml
controller/internal/translation/testdata/translation/policy_order.out.yml
controller/internal/translation/testdata/translation/virtualservice_embedded_mode.in.yml
controller/internal/translation/testdata/translation/virtualservice_embedded_mode.out.yml
controller/internal/translation/translation_test.go
site/content/en/docs/concept/filterpolicy.md
site/content/zh-hans/docs/concept/filterpolicy.md

chore: clarify the priority of embedded mode FilterPolicy

---

maintainer/feature_maturity_level.yaml
site/content/en/docs/reference/plugins/network_rbac.md
site/content/zh-hans/docs/reference/plugins/network_rbac.md
types/plugins/plugins_test.go

doc: add missing networkRBAC plugin

---

api/internal/consumer/consumer.go
api/pkg/filtermanager/api/phase.go
api/pkg/filtermanager/config.go
api/pkg/filtermanager/filtermanager.go
api/pkg/filtermanager/filtermanager_benchmark_test.go
api/pkg/filtermanager/filtermanager_test.go
api/pkg/filtermanager/model/model.go
api/pkg/plugins/plugins.go
api/pkg/plugins/type.go
types/plugins/demo/config.go

add method to control if a phase can be run synchronously

---

api/internal/consumer/consumer.go
api/pkg/filtermanager/api/phase.go
api/pkg/filtermanager/filtermanager.go

chore: refactor canSkipMethods logic

---

api/pkg/filtermanager/filtermanager.go
api/pkg/filtermanager/filtermanager_test.go

fix: canSyncRun should consider header processing when handling buffered data

---

api/plugins/tests/integration/controlplane/control_plane.go
api/plugins/tests/integration/dataplane/data_plane.go
api/plugins/tests/integration/dataplane/plugins.go

Fix the flaky test TestFilterManagerEncode.

test: improve the config change detection

---

.github/workflows/test.yml
api/Makefile
api/plugins/tests/integration/dataplane/binary_mode.go
api/plugins/tests/integration/dataplane/bootstrap.go
api/plugins/tests/integration/dataplane/data_plane.go
api/plugins/tests/integration/test_binary_mode.sh
api/plugins/tests/integration/testdata/Dockerfile
site/content/en/docs/developer-guide/plugin_integration_test_framework.md
site/content/zh-hans/docs/developer-guide/plugin_integration_test_framework.md

test: support running integration test with envoy bin

---

.golangci.yml
Makefile

The deadline option is dropped since golangci-lint v1.57: https://github.com/golangci/golangci-lint/blob/e0e37c43762068149116bcd69b305c1ca05647ae/CHANGELOG.md?plain=1#L319

ci: drop removed deadline option

---

site/content/en/docs/reference/plugins/cors.md
site/content/zh-hans/docs/reference/plugins/cors.md
types/plugins/cors/config.go
types/plugins/cors/config_test.go

fix(cors): allowOriginStringMatch & allowMethods are required

---

.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/website.yml
api/tests/integration/testdata/services/grpc/Dockerfile
common.mk
controller/tests/testdata/services/docker-compose.yml
e2e/base/nacos.yml
examples/dev_your_plugin/Makefile

ci: don't use unstable mirror

---

api/plugins/tests/integration/controlplane/control_plane.go
api/plugins/tests/integration/dataplane/bootstrap.go
api/plugins/tests/integration/dataplane/bootstrap_test.go
api/plugins/tests/integration/dataplane/testdata/listener.yml

add more methods to control bootstrap config

---

patch/README.md
patch/istio/1.21/20241224-fix-proto-panic.patch

Fix crash due to shared mutable state in EnvoyFilte #[53590](https://github.com/istio/istio/issues/53590)

Fix crash due to shared mutable state in EnvoyFilter #53594 

---

plugins/plugins/opa/config.go
plugins/plugins/opa/filter.go
plugins/plugins/opa/filter_test.go
plugins/tests/integration/opa_test.go
plugins/tests/integration/testdata/services/docker-compose.yml
plugins/tests/integration/testdata/services/opa/test.rego
site/content/en/docs/reference/plugins/opa.md
site/content/zh-hans/docs/reference/plugins/opa.md

Fix #48
This PR add support for custom response
- Added support for `custom_response` in both local and remote OPA services.
- Added unit tests for `custom_response` handling.
- Added integration tests for `custom_response`.
- Added English and Chinese documentation for `custom_response`.

opa: add ability to pass the auth response to the client response when denied
